### ISSUE TITLE
Switch to non-polymorphic variant ?

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/rresult#1]
@yminsky makes the point that it makes the type a little bit easier to use (avoid subtyping and problems due to polyvar inference). 

The loss would be a tighter coupling between clients and this module. But if we can get this line 

``` ocaml
type ('a, 'b) result = Ok of 'a | Error of 'b
```

in `Pervasives`, the point becomes moot.

**Comment by rgrinberg** [comment]
Are there any proposals to add `result` to Pervasives?

**Comment by dbuenzli** [comment]
Not yet. We were discussing this with @yminsky.

**Comment by yminsky** [comment]
There is now.

https://github.com/ocaml/ocaml/pull/147
