### ISSUE TITLE
map and bind are the wrong way around

### ISSUE THREAD

**Issue by Drup** [dbuenzli/rresult#14]
At the moment, the arguments are flipped, this doesn't follow the usual convention.

If you want to put them like that, at least give them labels.

**Comment by dbuenzli** [comment]
Maybe `map` could be changed but `bind` does follow the usual convention.

**Comment by Drup** [comment]
Oh, indeed, it's the right order for bind. What's the usual name for the flipped one ?

**Comment by dbuenzli** [comment]
> What's the usual name for the flipped one ?

Don't know, can't seem to find one. 

I'm a little bit reluctant to introduce labels as it tends to break higher-order usage of the functions.

**Comment by Drup** [comment]
I tend to agree, I would prefer for map just to be flipped.

**Comment by dbuenzli** [comment]
> I would prefer for map just to be flipped.

No strong objection. Just find it bit weird that `map` and `>>|` won't have the same argument order.

**Comment by dbuenzli** [comment]
Note that from the lib's mentioned [here](https://github.com/ocaml/ocaml/pull/147) only `CCError` uses the order you mention.

**Comment by Drup** [comment]
Tbh, I don't really care about what the other error libs are doing. I only use one. I, however, use numerous libraries and data structures that all put the function first. :)

**Comment by Drup** [comment]
(also: BatError also use the same order, with a first default argument, and core uses labels, as usual)

**Comment by dbuenzli** [comment]
> Tbh, I don't really care about what the other error libs are doing. I only use one

Well this contradicts the first sentence of this issue.

**Comment by Drup** [comment]
Does it ? I'm talking about the convention for functors (not the OCaml ones) and monads. Not the convention for specific error types.

**Comment by dbuenzli** [comment]
Given that most other libraries have `map` the way it is now, people functorizing over an error monad in ocaml are more likely to use the current signature (though in practice they only need `bind`).

**Comment by Drup** [comment]
> Given that most other libraries have map the way it is now

Except they don't, they all have a slightly different version.
- containers: `val map : ('a -> 'b) -> ('a, 'err) t -> ('b, 'err) t` (function first)
- batteries: `val map_default : 'b -> ('a -> 'b) -> ('a, _) t -> 'b` (function first, with a default arg)
- core : `val map : ('ok, 'err) t -> f:('ok -> 'c) -> ('c , 'err) t` (label)
- pvem `val map: ('a, 'b) t -> ('a -> 'c) -> ('c, 'b) t` (function last)

You have to redefine most of it to functorize anyway. The one you choose for Rresult really doesn't matter (from a functorization point of view, at least).

**Comment by dbuenzli** [comment]
Decided to use haskell's convention.
