### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hongchangwu** [dbuenzli/rresult#22]
Can we cut a new release for opam?

The latest one in opam doesn't have `R.failwith_error_msg`introduced in #21

**Comment by dbuenzli** [comment]
I can do that but I think I'll rename the function to `R.failwith_error`.

**Comment by dbuenzli** [comment]
Or maybe not in fact...

**Comment by dbuenzli** [comment]
See https://github.com/ocaml/opam-repository/pull/12760

**Comment by dbuenzli** [comment]
Sorry that may take a bit longer because somehow opam's dev decided to break the `opam-publish` workflow that `topkg` uses without any notice.
