### ISSUE TITLE
Do not squat the `Result` toplevel name.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/rresult#6]

**Comment by dbuenzli** [comment]
Fixes concern raised by @yminsky in https://github.com/ocaml/ocaml/pull/147

**Comment by dbuenzli** [comment]
Don't like the new name it feels noisy in interfaces.

**Comment by toots** [comment]
+1 see http://caml.inria.fr/mantis/view.php?id=6871

**Comment by dbuenzli** [comment]
@toots That doesn't seem related or do you have a `Result` module in your code base ?
